//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace MultipleServCharac
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BLEServiceContainer
	{
	/*	public int uuid
		{
			get;
			set;
		}

        public IEnumerable<BLECharacteristicContainer> BLECharacteristicContainer
		{
			get;
			set;
		}
        */
	}
}

