//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace MultipleServCharac
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Model
	{
        private MultipleServCharac.BLEServiceContainer serviceContainer;


        public Model()
        {
            serviceContainer = new BLEServiceContainer();
        }

		public virtual int serviceHandleStart
		{
			get;
			set;
		}

		public virtual int serviceHandleEnd
		{
			get;
			set;
		}

		public Object o
		{
			get;
			set;
		}

		public virtual BLEServiceContainer BLEServiceContainer
		{
            get
            {
             return serviceContainer   ;
            }
			//set;
		}

	}
}

